extends RefCounted

const DEFAULT_LANGUAGE := "hu"

const TRANSLATIONS := {
	"hu": {
		"hud.level": "Szint {level}",
		"hud.hunger": "Éhség",
		"hud.happiness": "Boldogság",
		"hud.energy": "Energia",
		"hud.shop": "Shop",
		"hud.play": "Play",
		"hud.skins": "Skinek",
		"hud.bathroom": "Fürdő",
		"shop.tab.food": "Food",
		"shop.tab.toys": "Játékok",
		"shop.tab.furniture": "Szobák",
		"shop.tab.skins": "Skinek",
		"shop.tab.special": "Extra",
		"shop.daily_deal": "Napi ajánlat",
		"shop.today_only": "Ma csak: {bonus}",
		"shop.refresh_in": "Frissül: {time}",
		"shop.check_back_later": "Nézz vissza később",
		"shop.soon": "Hamarosan",
		"shop.owned": "Megvan",
		"shop.selected": "Kiválasztva",
		"shop.select": "Kiválaszt",
		"shop.buy": "Megvesz",
		"shop.claimed": "Elvitte",
		"shop.bonus.style_unlock": "Új kinézet",
		"shop.bonus.room_theme": "Szoba téma",
		"shop.bonus.cute_surprise": "Cuki meglepetés",
		"shop.stat.hunger": "éhség",
		"shop.stat.happiness": "boldogság",
		"shop.stat.energy": "energia",
		"shop.food.message.1": "Nyami! Ez nagyon jól néz ki!",
		"shop.food.message.2": "Ez az! Már éhes voltam!",
		"shop.food.message.3": "Hmm... ezt most rögtön megeszem!",
		"shop.food.message.4": "Imádom az ilyen finomságokat!",
		"shop.food.message.5": "Ez tuti kedvenc lesz!",
		"shop.toy.message.1": "Játszunk! Játszunk!",
		"shop.toy.message.2": "Ez menő! Kipróbálhatom?",
		"shop.toy.message.3": "Ez lesz az új kedvenc játékom!",
		"shop.toy.message.4": "Ezzel biztos jól fogunk szórakozni!",
		"shop.toy.message.5": "Dobd ide! Dobd ide!",
		"bathroom.clean.start": "Szappan, zuhany, törölköző. Husi mindjárt ragyogni fog!",
		"bathroom.clean.finished": "Husi csillogóan tiszta lett!",
		"bathroom.clean.alreadyClean": "Husi már tiszta!",
		"bathroom.clean.message.1": "Ez most aztán jólesett!",
		"bathroom.clean.message.2": "Puha és tiszta vagyok!",
		"bathroom.clean.message.3": "Most nagyon frissnek érzem magam!",
		"bathroom.clean.message.4": "Illatos lettem, ugye?",
		"bathroom.clean.message.5": "Jöhetnek az ölelések!",
		"settings.title": "Beállítások",
		"settings.language": "Nyelv",
		"settings.audio": "Hangok",
		"settings.master": "Fő hangerő",
		"settings.effects": "Effektek",
		"settings.exit": "Kilépés",
		"settings.scoreboard": "Scoreboard",
		"settings.tray_exit": "Kilépés a tálcára",
		"settings.home_exit": "Kilépés főmenüre",
		"settings.close": "Bezárás",
		"settings.language_set": "Nyelv: {language}",
		"settings.tray_unavailable": "A tálcára küldés ebben a buildben nincs bekötve.",
		"settings.scoreboard_title": "Scoreboard",
		"settings.ok": "OK",
		"settings.scoreboard_body": "Legjobb minijáték pont: {best_score}\nCoinok: {coins}\nSzint: {level}\nSkinek: {skins}\nSzobák: {rooms}\nÉhség: {hunger}%\nBoldogság: {happiness}%\nEnergia: {energy}%",
		"minigame.level_score": "Szint {level} - Pont: {score}",
		"minigame.level_up": "SZINTLÉPÉS!",
		"minigame.pause": "Szünet",
		"minigame.resume": "Folytatás",
		"minigame.game_over": "VÉGE",
		"minigame.restart": "Újra",
		"minigame.back": "Vissza",
		"minigame.virtual_coins": "+{amount} virtuális coin",
		"minigame.jet_boost": "JET BOOST!",
		"main.need_feed": "{cost} coin kell az etetéshez.",
		"main.fed_pet": "Meg lett etetve.",
		"main.daily_claimed_already": "A napi ajánlatot már elvitted.",
		"main.not_enough_coins": "Nincs elég coin.",
		"main.unlocked": "{item} feloldva!",
		"main.used": "{item} használva.",
		"main.selected": "{item} kiválasztva.",
		"main.daily_claimed": "Napi ajánlat elvive!",
		"main.coins_plus": "+{amount} coin",
		"item.fishSnack": "Halas snack",
		"item.premiumMeat": "Prémium hús",
		"item.cookie": "Süti",
		"item.milk": "Tej",
		"item.iceCream": "Fagyi",
		"item.goldenTreat": "Arany falat",
		"item.ball": "Labdázás",
		"item.rope": "Kötélhúzás",
		"item.teddy": "Plüssmaci",
		"item.rubberChicken": "Gumi csirke",
		"item.boneToy": "Rágócsont",
		"item.pawCup": "Pohárka",
		"item.beach": "Tengerparti szoba",
		"item.nightRoom": "Éjjeli kuckó",
		"item.halloween": "Halloween kuckó",
		"item.xmas": "Karácsonyi szoba",
		"item.default": "Alap Husi",
		"item.cool": "Menő Husi",
		"item.legend": "Legendás Husi",
		"item.mealBox": "Meal Box",
		"item.megaCookie": "Mega süti",
		"item.energyShake": "Energia shake",
		"item.royalTreat": "Királyi falat",
		"item.coolSpecial": "Menő Husi+",
		"item.legendSpecial": "Legendás Husi+"
	},
	"en": {
		"hud.level": "Level {level}",
		"hud.hunger": "Hunger",
		"hud.happiness": "Happiness",
		"hud.energy": "Energy",
		"hud.shop": "Shop",
		"hud.play": "Play",
		"hud.skins": "Skins",
		"hud.bathroom": "Bathroom",
		"shop.tab.food": "Food",
		"shop.tab.toys": "Toys",
		"shop.tab.furniture": "Rooms",
		"shop.tab.skins": "Skins",
		"shop.tab.special": "Special",
		"shop.daily_deal": "Daily Deal",
		"shop.today_only": "{bonus} today only!",
		"shop.refresh_in": "Refresh in {time}",
		"shop.check_back_later": "Check back later",
		"shop.soon": "Soon",
		"shop.owned": "Owned",
		"shop.selected": "Selected",
		"shop.select": "Select",
		"shop.buy": "Buy",
		"shop.claimed": "Claimed",
		"shop.bonus.style_unlock": "Style Unlock",
		"shop.bonus.room_theme": "Room Theme",
		"shop.bonus.cute_surprise": "Cute surprise",
		"shop.stat.hunger": "Hunger",
		"shop.stat.happiness": "Happiness",
		"shop.stat.energy": "Energy",
		"shop.food.message.1": "Yum! This looks really good!",
		"shop.food.message.2": "Yes! I was getting hungry!",
		"shop.food.message.3": "Hmm... I'm eating this right away!",
		"shop.food.message.4": "I love treats like this!",
		"shop.food.message.5": "This is definitely a new favorite!",
		"shop.toy.message.1": "Let's play! Let's play!",
		"shop.toy.message.2": "This is so cool! Can I try it?",
		"shop.toy.message.3": "This will be my new favorite toy!",
		"shop.toy.message.4": "We're going to have so much fun with this!",
		"shop.toy.message.5": "Throw it here! Throw it here!",
		"bathroom.clean.start": "Soap, shower, towel. Husi will sparkle in no time!",
		"bathroom.clean.finished": "Husi is all clean and shiny!",
		"bathroom.clean.alreadyClean": "Husi is already clean!",
		"bathroom.clean.message.1": "That felt amazing!",
		"bathroom.clean.message.2": "I'm so soft and clean now!",
		"bathroom.clean.message.3": "I feel super fresh now!",
		"bathroom.clean.message.4": "I smell wonderful, right?",
		"bathroom.clean.message.5": "Bring on the cuddles!",
		"settings.title": "Settings",
		"settings.language": "Language",
		"settings.audio": "Audio",
		"settings.master": "Master",
		"settings.effects": "Effects",
		"settings.exit": "Exit",
		"settings.scoreboard": "Scoreboard",
		"settings.tray_exit": "Exit to tray",
		"settings.home_exit": "Exit to home",
		"settings.close": "Close",
		"settings.language_set": "Language: {language}",
		"settings.tray_unavailable": "Tray minimize is not available in this build.",
		"settings.scoreboard_title": "Scoreboard",
		"settings.ok": "OK",
		"settings.scoreboard_body": "Best minigame score: {best_score}\nCoins: {coins}\nLevel: {level}\nSkins: {skins}\nRooms: {rooms}\nHunger: {hunger}%\nHappiness: {happiness}%\nEnergy: {energy}%",
		"minigame.level_score": "Level {level} - Score: {score}",
		"minigame.level_up": "LEVEL UP!",
		"minigame.pause": "Pause",
		"minigame.resume": "Resume",
		"minigame.game_over": "GAME OVER",
		"minigame.restart": "Restart",
		"minigame.back": "Back",
		"minigame.virtual_coins": "+{amount} virtual coins",
		"minigame.jet_boost": "JET BOOST!",
		"main.need_feed": "Need {cost} coins to feed.",
		"main.fed_pet": "Fed pet.",
		"main.daily_claimed_already": "Daily deal already claimed.",
		"main.not_enough_coins": "Not enough coins.",
		"main.unlocked": "{item} unlocked!",
		"main.used": "Used {item}.",
		"main.selected": "{item} selected.",
		"main.daily_claimed": "Daily deal claimed!",
		"main.coins_plus": "+{amount} coins",
		"item.fishSnack": "Fish Snack",
		"item.premiumMeat": "Premium Meat",
		"item.cookie": "Cookie",
		"item.milk": "Milk",
		"item.iceCream": "Ice Cream",
		"item.goldenTreat": "Golden Treat",
		"item.ball": "Ball Toss",
		"item.rope": "Rope Tug",
		"item.teddy": "Teddy Bear",
		"item.rubberChicken": "Rubber Chicken",
		"item.boneToy": "Chew Bone",
		"item.pawCup": "Paw Cup",
		"item.beach": "Beach House",
		"item.nightRoom": "Moonlight Loft",
		"item.halloween": "Spooky Den",
		"item.xmas": "Snowy Suite",
		"item.default": "Classic Pup",
		"item.cool": "Cool Pup",
		"item.legend": "Legend Pup",
		"item.mealBox": "Meal Box",
		"item.megaCookie": "Mega Cookie",
		"item.energyShake": "Energy Shake",
		"item.royalTreat": "Royal Treat",
		"item.coolSpecial": "Cool Pup+",
		"item.legendSpecial": "Legend Pup+"
	},
	"de": {
		"hud.level": "Level {level}",
		"hud.hunger": "Hunger",
		"hud.happiness": "Freude",
		"hud.energy": "Energie",
		"hud.shop": "Shop",
		"hud.play": "Spiel",
		"hud.skins": "Skins",
		"hud.bathroom": "Bad",
		"shop.tab.food": "Futter",
		"shop.tab.toys": "Spielzeug",
		"shop.tab.furniture": "Zimmer",
		"shop.tab.skins": "Skins",
		"shop.tab.special": "Extra",
		"shop.daily_deal": "Tagesdeal",
		"shop.today_only": "Nur heute: {bonus}",
		"shop.refresh_in": "Neu in {time}",
		"shop.check_back_later": "Später wiederkommen",
		"shop.soon": "Bald",
		"shop.owned": "Besitzt",
		"shop.selected": "Ausgewählt",
		"shop.select": "Wählen",
		"shop.buy": "Kaufen",
		"shop.claimed": "Geholt",
		"shop.bonus.style_unlock": "Neuer Stil",
		"shop.bonus.room_theme": "Zimmerstil",
		"shop.bonus.cute_surprise": "Süße Überraschung",
		"shop.stat.hunger": "Hunger",
		"shop.stat.happiness": "Freude",
		"shop.stat.energy": "Energie",
		"shop.food.message.1": "Mjam! Das sieht richtig lecker aus!",
		"shop.food.message.2": "Yes! Ich hatte schon Hunger!",
		"shop.food.message.3": "Hmm... das esse ich sofort!",
		"shop.food.message.4": "Ich liebe solche Leckereien!",
		"shop.food.message.5": "Das wird bestimmt mein Favorit!",
		"shop.toy.message.1": "Spielen wir! Spielen wir!",
		"shop.toy.message.2": "Wie cool! Darf ich es ausprobieren?",
		"shop.toy.message.3": "Das wird mein neues Lieblingsspielzeug!",
		"shop.toy.message.4": "Damit werden wir bestimmt viel Spaß haben!",
		"shop.toy.message.5": "Wirf es her! Wirf es her!",
		"bathroom.clean.start": "Seife, Dusche, Handtuch. Husi wird gleich strahlen!",
		"bathroom.clean.finished": "Husi ist blitzsauber!",
		"bathroom.clean.alreadyClean": "Husi ist schon sauber!",
		"bathroom.clean.message.1": "Das hat richtig gutgetan!",
		"bathroom.clean.message.2": "Ich bin jetzt so weich und sauber!",
		"bathroom.clean.message.3": "Jetzt fühle ich mich herrlich frisch!",
		"bathroom.clean.message.4": "Ich dufte toll, oder?",
		"bathroom.clean.message.5": "Her mit den Kuscheleinheiten!",
		"settings.title": "Einstellungen",
		"settings.language": "Sprache",
		"settings.audio": "Audio",
		"settings.master": "Gesamt",
		"settings.effects": "Effekte",
		"settings.exit": "Beenden",
		"settings.scoreboard": "Scoreboard",
		"settings.tray_exit": "In Tray senden",
		"settings.home_exit": "Zum Startmenü",
		"settings.close": "Schließen",
		"settings.language_set": "Sprache: {language}",
		"settings.tray_unavailable": "Tray-Funktion ist in diesem Build nicht verfügbar.",
		"settings.scoreboard_title": "Scoreboard",
		"settings.ok": "OK",
		"settings.scoreboard_body": "Bester Minigame-Score: {best_score}\nCoins: {coins}\nLevel: {level}\nSkins: {skins}\nZimmer: {rooms}\nHunger: {hunger}%\nFreude: {happiness}%\nEnergie: {energy}%",
		"minigame.level_score": "Level {level} - Punkte: {score}",
		"minigame.level_up": "LEVEL UP!",
		"minigame.pause": "Pause",
		"minigame.resume": "Weiter",
		"minigame.game_over": "GAME OVER",
		"minigame.restart": "Neu",
		"minigame.back": "Zurück",
		"minigame.virtual_coins": "+{amount} virtuelle Coins",
		"minigame.jet_boost": "JET BOOST!",
		"main.need_feed": "{cost} Coins zum Füttern nötig.",
		"main.fed_pet": "Haustier gefüttert.",
		"main.daily_claimed_already": "Tagesdeal schon geholt.",
		"main.not_enough_coins": "Nicht genug Coins.",
		"main.unlocked": "{item} freigeschaltet!",
		"main.used": "{item} benutzt.",
		"main.selected": "{item} ausgewählt.",
		"main.daily_claimed": "Tagesdeal geholt!",
		"main.coins_plus": "+{amount} Coins",
		"item.fishSnack": "Fisch-Snack",
		"item.premiumMeat": "Premium-Fleisch",
		"item.cookie": "Keks",
		"item.milk": "Milch",
		"item.iceCream": "Eiscreme",
		"item.goldenTreat": "Goldener Snack",
		"item.ball": "Ballspiel",
		"item.rope": "Seilziehen",
		"item.teddy": "Teddybär",
		"item.rubberChicken": "Gummihuhn",
		"item.boneToy": "Kauknochen",
		"item.pawCup": "Pfotenbecher",
		"item.beach": "Strandhaus",
		"item.nightRoom": "Mondschein-Loft",
		"item.halloween": "Spukhöhle",
		"item.xmas": "Schneezimmer",
		"item.default": "Klassischer Husi",
		"item.cool": "Cooler Husi",
		"item.legend": "Legendärer Husi",
		"item.mealBox": "Mahlzeitenbox",
		"item.megaCookie": "Mega-Keks",
		"item.energyShake": "Energie-Shake",
		"item.royalTreat": "Königlicher Snack",
		"item.coolSpecial": "Cooler Husi+",
		"item.legendSpecial": "Legendärer Husi+"
	},
	"uk": {
		"hud.level": "Рівень {level}",
		"hud.hunger": "Голод",
		"hud.happiness": "Щастя",
		"hud.energy": "Енергія",
		"hud.shop": "Shop",
		"hud.play": "Грати",
		"hud.skins": "Скіни",
		"hud.bathroom": "Ванна",
		"shop.tab.food": "Їжа",
		"shop.tab.toys": "Іграшки",
		"shop.tab.furniture": "Кімнати",
		"shop.tab.skins": "Скіни",
		"shop.tab.special": "Особливе",
		"shop.daily_deal": "Щоденна знижка",
		"shop.today_only": "Лише сьогодні: {bonus}",
		"shop.refresh_in": "Оновлення через {time}",
		"shop.check_back_later": "Зайди пізніше",
		"shop.soon": "Скоро",
		"shop.owned": "Є",
		"shop.selected": "Обране",
		"shop.select": "Обрати",
		"shop.buy": "Купити",
		"shop.claimed": "Отримано",
		"shop.bonus.style_unlock": "Новий стиль",
		"shop.bonus.room_theme": "Тема кімнати",
		"shop.bonus.cute_surprise": "Мила несподіванка",
		"shop.stat.hunger": "голод",
		"shop.stat.happiness": "щастя",
		"shop.stat.energy": "енергія",
		"shop.food.message.1": "Ням! Це виглядає дуже смачно!",
		"shop.food.message.2": "О так! Я вже зголоднів!",
		"shop.food.message.3": "Хмм... я з'їм це просто зараз!",
		"shop.food.message.4": "Обожнюю такі смаколики!",
		"shop.food.message.5": "Це точно стане улюбленим!",
		"shop.toy.message.1": "Граймо! Граймо!",
		"shop.toy.message.2": "Оце круто! Можна спробувати?",
		"shop.toy.message.3": "Це буде моя нова улюблена іграшка!",
		"shop.toy.message.4": "З цим нам точно буде весело!",
		"shop.toy.message.5": "Кидай сюди! Кидай сюди!",
		"bathroom.clean.start": "Мило, душ, рушник. Хусі зараз засяє!",
		"bathroom.clean.finished": "Хусі тепер чистенький і блискучий!",
		"bathroom.clean.alreadyClean": "Хусі вже чистий!",
		"bathroom.clean.message.1": "Ох, як же це приємно!",
		"bathroom.clean.message.2": "Я такий м'який і чистий!",
		"bathroom.clean.message.3": "Тепер я почуваюся зовсім свіженьким!",
		"bathroom.clean.message.4": "Правда ж, я чудово пахну?",
		"bathroom.clean.message.5": "Час для обіймів!",
		"settings.title": "Налаштування",
		"settings.language": "Мова",
		"settings.audio": "Звуки",
		"settings.master": "Загальна гучність",
		"settings.effects": "Ефекти",
		"settings.exit": "Вихід",
		"settings.scoreboard": "Scoreboard",
		"settings.tray_exit": "Згорнути в трей",
		"settings.home_exit": "До головного меню",
		"settings.close": "Закрити",
		"settings.language_set": "Мова: {language}",
		"settings.tray_unavailable": "Згортання в трей недоступне в цій збірці.",
		"settings.scoreboard_title": "Scoreboard",
		"settings.ok": "OK",
		"settings.scoreboard_body": "Найкращий рахунок: {best_score}\nМонети: {coins}\nРівень: {level}\nСкіни: {skins}\nКімнати: {rooms}\nГолод: {hunger}%\nЩастя: {happiness}%\nЕнергія: {energy}%",
		"minigame.level_score": "Рівень {level} - Очки: {score}",
		"minigame.level_up": "РІВЕНЬ ВГОРУ!",
		"minigame.pause": "Пауза",
		"minigame.resume": "Продовжити",
		"minigame.game_over": "КІНЕЦЬ ГРИ",
		"minigame.restart": "Знову",
		"minigame.back": "Назад",
		"minigame.virtual_coins": "+{amount} віртуальних монет",
		"minigame.jet_boost": "JET BOOST!",
		"main.need_feed": "Потрібно {cost} монет для годування.",
		"main.fed_pet": "Улюбленця нагодовано.",
		"main.daily_claimed_already": "Щоденну знижку вже забрано.",
		"main.not_enough_coins": "Недостатньо монет.",
		"main.unlocked": "{item} відкрито!",
		"main.used": "{item} використано.",
		"main.selected": "{item} обрано.",
		"main.daily_claimed": "Щоденну знижку забрано!",
		"main.coins_plus": "+{amount} монет",
		"item.fishSnack": "Рибний снек",
		"item.premiumMeat": "Преміальне м'ясо",
		"item.cookie": "Печиво",
		"item.milk": "Молоко",
		"item.iceCream": "Морозиво",
		"item.goldenTreat": "Золотий смаколик",
		"item.ball": "Гра в м'яч",
		"item.rope": "Перетягування каната",
		"item.teddy": "Плюшевий ведмедик",
		"item.rubberChicken": "Гумова курка",
		"item.boneToy": "Кісточка для жування",
		"item.pawCup": "Лапко-чашка",
		"item.beach": "Пляжна кімната",
		"item.nightRoom": "Місячний лофт",
		"item.halloween": "Моторошне лігво",
		"item.xmas": "Сніжний люкс",
		"item.default": "Класичний Хусі",
		"item.cool": "Крутий Хусі",
		"item.legend": "Легендарний Хусі",
		"item.mealBox": "Коробка їжі",
		"item.megaCookie": "Мега-печиво",
		"item.energyShake": "Енергетичний шейк",
		"item.royalTreat": "Королівський смаколик",
		"item.coolSpecial": "Крутий Хусі+",
		"item.legendSpecial": "Легендарний Хусі+"
	},
	"zh": {
		"hud.level": "等级 {level}",
		"hud.hunger": "饥饿",
		"hud.happiness": "快乐",
		"hud.energy": "能量",
		"hud.shop": "商店",
		"hud.play": "玩耍",
		"hud.skins": "皮肤",
		"hud.bathroom": "浴室",
		"shop.tab.food": "食物",
		"shop.tab.toys": "玩具",
		"shop.tab.furniture": "房间",
		"shop.tab.skins": "皮肤",
		"shop.tab.special": "特别",
		"shop.daily_deal": "每日优惠",
		"shop.today_only": "仅限今日：{bonus}",
		"shop.refresh_in": "{time} 后刷新",
		"shop.check_back_later": "稍后再来",
		"shop.soon": "即将推出",
		"shop.owned": "已拥有",
		"shop.selected": "已选择",
		"shop.select": "选择",
		"shop.buy": "购买",
		"shop.claimed": "已领取",
		"shop.bonus.style_unlock": "新外观",
		"shop.bonus.room_theme": "房间主题",
		"shop.bonus.cute_surprise": "可爱惊喜",
		"shop.stat.hunger": "饥饿",
		"shop.stat.happiness": "快乐",
		"shop.stat.energy": "能量",
		"shop.food.message.1": "好香呀！看起来真好吃！",
		"shop.food.message.2": "太好了！我刚好饿了！",
		"shop.food.message.3": "嗯……这个我要马上吃掉！",
		"shop.food.message.4": "我最喜欢这种美味啦！",
		"shop.food.message.5": "这肯定会变成我的最爱！",
		"shop.toy.message.1": "来玩吧！来玩吧！",
		"shop.toy.message.2": "太酷了！我可以试试吗？",
		"shop.toy.message.3": "这会成为我新的最爱玩具！",
		"shop.toy.message.4": "有了这个我们一定会玩得超开心！",
		"shop.toy.message.5": "快丢过来！快丢过来！",
		"bathroom.clean.start": "先抹香皂，再冲一冲，最后擦干。Husi 很快就会闪闪发亮！",
		"bathroom.clean.finished": "Husi 已经变得干净又亮晶晶啦！",
		"bathroom.clean.alreadyClean": "Husi 已经很干净啦！",
		"bathroom.clean.message.1": "洗得真舒服呀！",
		"bathroom.clean.message.2": "我现在又软又干净！",
		"bathroom.clean.message.3": "现在感觉清爽极了！",
		"bathroom.clean.message.4": "我闻起来很香，对吧？",
		"bathroom.clean.message.5": "快来抱抱我吧！",
		"settings.title": "设置",
		"settings.language": "语言",
		"settings.audio": "声音",
		"settings.master": "总音量",
		"settings.effects": "音效",
		"settings.exit": "退出",
		"settings.scoreboard": "排行榜",
		"settings.tray_exit": "最小化到托盘",
		"settings.home_exit": "返回主页",
		"settings.close": "关闭",
		"settings.language_set": "语言：{language}",
		"settings.tray_unavailable": "此版本不支持托盘最小化。",
		"settings.scoreboard_title": "排行榜",
		"settings.ok": "确定",
		"settings.scoreboard_body": "最佳小游戏分数：{best_score}\n金币：{coins}\n等级：{level}\n皮肤：{skins}\n房间：{rooms}\n饥饿：{hunger}%\n快乐：{happiness}%\n能量：{energy}%",
		"minigame.level_score": "等级 {level} - 分数：{score}",
		"minigame.level_up": "升级！",
		"minigame.pause": "暂停",
		"minigame.resume": "继续",
		"minigame.game_over": "游戏结束",
		"minigame.restart": "重新开始",
		"minigame.back": "返回",
		"minigame.virtual_coins": "+{amount} 虚拟金币",
		"minigame.jet_boost": "JET BOOST!",
		"main.need_feed": "喂食需要 {cost} 金币。",
		"main.fed_pet": "宠物已喂食。",
		"main.daily_claimed_already": "今日优惠已经领取。",
		"main.not_enough_coins": "金币不足。",
		"main.unlocked": "{item} 已解锁！",
		"main.used": "已使用 {item}。",
		"main.selected": "{item} 已选择。",
		"main.daily_claimed": "每日优惠已领取！",
		"main.coins_plus": "+{amount} 金币",
		"item.fishSnack": "鱼肉零食",
		"item.premiumMeat": "高级鲜肉",
		"item.cookie": "曲奇",
		"item.milk": "牛奶",
		"item.iceCream": "冰淇淋",
		"item.goldenTreat": "黄金零食",
		"item.ball": "抛球游戏",
		"item.rope": "拔河绳",
		"item.teddy": "泰迪熊",
		"item.rubberChicken": "橡胶小鸡",
		"item.boneToy": "磨牙骨头",
		"item.pawCup": "爪爪杯",
		"item.beach": "海滩小屋",
		"item.nightRoom": "月光阁楼",
		"item.halloween": "惊悚小窝",
		"item.xmas": "雪夜套房",
		"item.default": "经典 Husi",
		"item.cool": "酷酷 Husi",
		"item.legend": "传奇 Husi",
		"item.mealBox": "餐盒",
		"item.megaCookie": "超级曲奇",
		"item.energyShake": "能量奶昔",
		"item.royalTreat": "皇家零食",
		"item.coolSpecial": "酷酷 Husi+",
		"item.legendSpecial": "传奇 Husi+"
	}
}

static func text(language_code: String, key: String, args: Dictionary = {}) -> String:
	var language_map: Dictionary = TRANSLATIONS.get(language_code, TRANSLATIONS[DEFAULT_LANGUAGE])
	var fallback_map: Dictionary = TRANSLATIONS[DEFAULT_LANGUAGE]
	var value := str(language_map.get(key, fallback_map.get(key, key)))
	for arg_key in args.keys():
		value = value.replace("{%s}" % str(arg_key), str(args[arg_key]))
	return value

static func item_name(language_code: String, item_id: String, fallback: String = "") -> String:
	var key := "item.%s" % item_id
	var language_map: Dictionary = TRANSLATIONS.get(language_code, TRANSLATIONS[DEFAULT_LANGUAGE])
	if language_map.has(key):
		return str(language_map[key])
	if fallback != "":
		return fallback
	return str(TRANSLATIONS[DEFAULT_LANGUAGE].get(key, item_id))
